#!/bin/bash

if [[ "$EUID" -ne 0 ]]; then
    echo "No root alert!"
    exit
fi

if command -v layman1 &>/dev/null; then
    echo "Syncing layman overlays..."
    layman -S -q
fi

echo "Syncing emerge..."
emerge --sync -q

echo "Done."
