#!/bin/bash

if [[ "$EUID" -ne 0 ]]; then
    echo "No root alert!"
    exit
fi

esync() {
    if command -v layman &>/dev/null; then
        echo "Syncing layman overlays..."
        layman -S -q
    fi

    echo "Syncing emerge..."
    emerge --sync -q

    echo "Done."
}

case "$1" in
    sa)
        esync && emerge -auND --with-bdeps=y --keep-going=y @world
        ;;
    sav)
        esync && emerge -avuND --with-bdeps=y --keep-going=y @world
        ;;
    s)
        esync && emerge -avquND --with-bdeps=y --keep-going=y @world
        ;;
    a)
        emerge -auND --with-bdeps=y --keep-going=y @world
        ;;
    av)
        emerge -avuND --with-bdeps=y --keep-going=y @world
        ;;
    *)
        emerge -avquND --with-bdeps=y --keep-going=y @world
        ;;
esac
