#!/bin/bash

AUTO_SUDO=0

if [[ "$EUID" -ne 0 ]]; then
    if [[ "$AUTO_SUDO" -eq 1 ]]; then
        sudo "$0" "$@"
        exit $?
    else
        echo "No root alert!"
        echo "Run this command with sudo"
        exit
    fi
fi

if command -v layman &>/dev/null; then
    echo "Syncing layman overlays..."
    ausdo layman -S -q
fi

echo "Syncing repositories..."
emerge --sync -q

echo "Done."
