#!/bin/bash

AUTO_SUDO=0

function asudo() {
    if [[ "$AUTO_SUDO" -eq 1 ]]; then
        sudo $@
    else
        $@
    fi
}

if [[ "$EUID" -ne 0 && "$AUTO_SUDO" -eq 0 ]]; then
    echo "No root alert!"
    echo "Run this command with sudo"
    exit
fi

if command -v layman &>/dev/null; then
    echo "Syncing layman overlays..."
    ausdo layman -S -q
fi

echo "Syncing repositories..."
asudo emerge --sync -q

echo "Done."
