#!/bin/bash

AUTO_SUDO=0

function asudo() {
    if [[ "$AUTO_SUDO" -eq 1 ]]; then
        sudo $@
    else
        $@
    fi
}

if [[ "$EUID" -ne 0 && "$AUTO_SUDO" -eq 0 ]]; then
    echo "No root alert!"
    echo "Run this command with sudo"
    exit
fi

esync() {
    if command -v layman &>/dev/null; then
        echo "Syncing layman overlays..."
        asudo layman -S -q
    fi

    echo "Syncing repositories..."
    asudo emerge --sync -q

    echo "Done."
}

case "$1" in
    sa)
        esync && asudo emerge -auND --with-bdeps=y --keep-going=y @world
        ;;
    sav)
        esync && asudo emerge -avuND --with-bdeps=y --keep-going=y @world
        ;;
    s)
        esync && asudo emerge -avquND --with-bdeps=y --keep-going=y @world
        ;;
    a)
        asudo emerge -auND --with-bdeps=y --keep-going=y @world
        ;;
    av)
        asudo emerge -avuND --with-bdeps=y --keep-going=y @world
        ;;
    *)
        asudo emerge -avquND --with-bdeps=y --keep-going=y @world
        ;;
esac
