#!/bin/bash

AUTO_SUDO=0

COMMON_EMERGE_FLAGS=("--update" "--newuse" "--deep" "--with-bdeps=y" "--keep-going=y")
DEFAULT_EMERGE_FLAGS=("--ask" "--verbose" "--quiet")

asudo() {
    if [[ "$AUTO_SUDO" -eq 1 ]]; then
        sudo $@
    else
        $@
    fi
}

if [[ "$EUID" -ne 0 && "$AUTO_SUDO" -eq 0 ]]; then
    echo "No root alert!"
    echo "Run this command with sudo"
    exit
fi

esync() {
    if command -v layman &>/dev/null; then
        echo "Syncing layman overlays..."
        asudo layman -S -q
    fi

    echo "Syncing repositories..."
    asudo emerge --sync -q
}

show_help() {
    cat <<EOF

USAGE:
    ${0##*/} [options] [options without '-']

DESCRIPTION:
    Update script for emerge

OPTIONS:
    -h  Show this help message
    -s  Sync repositories (runs layman -S and emerge --sync)
    -a  Runs emerge with --sync flag (see man 1 emerge)
    -v  Runs emerge with --verbose flag (see man 1 emerge)
    -q  Runs emerge with --quiet flag (see man 1 emerge)
    -p  Runs emerge with --pretend flag (see man 1 emerge)
    -m  Runs emerge with --autounmask and --autounmask-write flags (see man 1 emerge)
    -d  Runs 'emerge --ask --quiet --depclean' after updating (see man 1 emerge)
    -c  Runs 'portpeek --all --fix-confirm' after updating to clean obsolete entries in /etc/portage/package.* (see man 1 portpeek)
EOF
}

sync=0
depclean=0
portpeek=0
emerge_flags=()

process_option() {
    case "$1" in
        h | \?)
            show_help
            exit
            ;;
        s)
            sync=1
            ;;
        a)
            emerge_flags+=("--ask")
            ;;
        v)
            emerge_flags+=("--verbose")
            ;;
        q)
            emerge_flags+=("--quiet")
            ;;
        p)
            emerge_flags+=("--pretend")
            ;;
        m)
            emerge_flags+=("--autounmask" "--autounmask-write")
            ;;
        d)
            depclean=1
            ;;
        c)
            portpeek=1
            ;;
    esac
}

OPTIND=1
while getopts "hsavqpmdc" opt; do
    process_option "$opt"
done
shift "$((OPTIND-1))"

if [[ -n "$1" && "$1" =~ ^[^-] ]]; then
    for i in $(seq 1 ${#1}); do
        process_option "${1:i-1:1}"
    done
    shift
fi

if [[ -z "$emerge_flags" ]]; then
    emerge_flags="${DEFAULT_EMERGE_FLAGS[@]}"
fi

if [[ "$sync" -eq 1 ]]; then
    esync
fi

echo "Running emerge..."
asudo emerge "${emerge_flags[@]}" "${COMMON_EMERGE_FLAGS[@]}" "$@" "@world"

if [[ "$depclean" -eq 1 ]]; then
    echo "Running depclean..."
    emerge --ask --quiet --depclean
fi

if [[ "$portpeek" -eq 1 ]]; then
    if command -v portpeek &>/dev/null; then
        echo "Removing obsolete entries in /etc/portage/package.* ..."
        portpeek --all --fix-confirm
    else
        echo "Failed to remove obsolete entries in /etc/portage/package.* ..." >&2
        echo "portpeek is not installed" >&2
        exit 1
    fi
fi
