#!/bin/bash

AUTO_SUDO=0
EMERGE_LOG_FILE="/var/log/emerge.log"

function asudo() {
    if [[ "$AUTO_SUDO" -eq 1 ]]; then
        sudo $@
    else
        $@
    fi
}

if [[ ! -r "$EMERGE_LOG_FILE" && "$AUTO_SUDO" -eq 0 ]]; then
    echo "Could not open logfile '$EMERGE_LOG_FILE': Permission denied"
    echo "Add your user to portage group or run this command with sudo"
    exit
fi

with_total=1

if [[ -z "$1" ]]; then
    list=$( qlist -CI | asudo xargs qlop -aM | sort -t " " -k 2 -rn )
elif [[ "$1" =~ ^[0-9]+$ ]]; then
    list=$( qlist -CI | asudo xargs qlop -aM | sort -t " " -k 2 -rn | head -n "$1" )
else
    list=$( qlist -CI | asudo xargs qlop -aM | sort -t " " -k 2 -rn | grep -i "$1" )
    with_total=0
fi

if [[ "$with_total" -eq 1 ]]; then
    for item in "${list[@]}"; do echo "$item"; done\
        | awk '{ total += $2; printf("%s ", substr($1, 1, length($1)-1)); system("date -u +%H:%M:%S -d @"$2); } END { printf "total "; system("date -u +%H:%M:%S -d @"total); }'\
        | cat -n\
        | column -tR1
else
    for item in "${list[@]}"; do echo "$item"; done\
        | awk '{ printf("%s ", substr($1, 1, length($1)-1)); system("date -u +%H:%M:%S -d @"$2); }'\
        | cat -n\
        | column -tR1
fi

