#!/bin/bash
#
# Command which helps to know about time estimation for installing packages
#
# Mikhail Golbakh (DakEnviy) <golbah@yandex.ru>
#
# See LICENSE for copyright information

AUTO_SUDO=0
EMERGE_LOG_FILE="/var/log/emerge.log"

if [[ ! -r "$EMERGE_LOG_FILE" ]]; then
    if [[ "$AUTO_SUDO" -eq 1 ]]; then
        sudo "$0" "$@"
        exit $?
    else
        echo "Could not open logfile '$EMERGE_LOG_FILE': Permission denied"
        echo "Add your user to portage group or run this command with sudo"
        exit
    fi
fi

with_total=1

if [[ -z "$1" ]]; then
    list=$( qlist -CI | xargs qlop -aM | sort -t " " -k 2 -rn )
elif [[ "$1" =~ ^[0-9]+$ ]]; then
    list=$( qlist -CI | xargs qlop -aM | sort -t " " -k 2 -rn | head -n "$1" )
else
    list=$( qlist -CI | xargs qlop -aM | sort -t " " -k 2 -rn | grep -i "$1" )
    with_total=0

    if [[ -z "${list[*]}" ]]; then
        echo "Package '$1' not found"
        exit
    fi
fi

if [[ "$with_total" -eq 1 ]]; then
    for item in "${list[@]}"; do echo "$item"; done\
        | awk '{ total += $2; printf("%s ", substr($1, 1, length($1)-1)); system("date -u +%H:%M:%S -d @"$2); } END { printf "total "; system("date -u +%H:%M:%S -d @"total); }'\
        | cat -n\
        | column -tR1
else
    for item in "${list[@]}"; do echo "$item"; done\
        | awk '{ printf("%s ", substr($1, 1, length($1)-1)); system("date -u +%H:%M:%S -d @"$2); }'\
        | cat -n\
        | column -tR1
fi

